stages:
    - build
    - build-unity-plugin

variables:
    VLC_UWP_LLVM_IMAGE: registry.videolan.org/vlc-debian-llvm-uwp:20200706065223
    VLC_WIN_LLVM_IMAGE: registry.videolan.org/vlc-debian-llvm-mingw:20200703084018
    VLC_ANDROID_IMAGE: registry.videolan.org/vlc-debian-android:20190717134531

.base-template:
    tags:
        - docker
        - amd64
    stage: build
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

# Android

.variables-android-arm: &variables-android-arm
        ANDROID_ARCH: arm
        TRIPLET: arm-linux-androideabi

.android-common:
    extends: .base-template
    image:
        name: $VLC_ANDROID_IMAGE
    script: |
        git clone https://code.videolan.org/videolan/vlc/ && cd vlc
        wget https://code.videolan.org/videolan/vlc-android/raw/0daaf5f3a08b5c52b4caaf526633cca7061d04c2/compile-libvlc.sh
        if [ -n "$VLC_PREBUILT_CONTRIBS_URL" ]; then
            /bin/sh ./compile-libvlc.sh -a $ANDROID_ARCH --with-prebuilt-contribs
        else
            /bin/sh ./compile-libvlc.sh -a $ANDROID_ARCH --package-contribs
        fi

android-arm:
    extends: .android-common
    variables: *variables-android-arm
        
# Windows

.win-common:
    extends: .base-template
    script:
        - git clone https://code.videolan.org/videolan/vlc/ && cd vlc && extras/package/win32/build.sh $ARGS 
    after_script:
        - mkdir nightlies
        - cd ./vlc/$BUILD_FOLDER
        - make package-win-common
        - ls vlc-4.0.0-dev
        - 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on $ARTIFACT $OUTPUT
        - cp $ARTIFACT ../../nightlies
    variables:
        WINE_SDK_PATH: /usr/include/wine/wine/windows/
        OUTPUT: ./vlc-4.0.0-dev

.build-plugin-base:
    extends: .base-template
    image: registry.videolan.org/vlc-debian-llvm-mingw:20200703084018
    dependencies: 
        - libvlc-x86_64
    stage: build-unity-plugin
    script:
        - 7z x ./nightlies/vlc-4.0.0-dev-win64.7z -o./build
        - mkdir -p Assets/VLCUnity/Plugins/x86_64
        - cp -R ./build/vlc-4.0.0-dev/{libvlc.dll,libvlccore.dll,hrtfs,lua,plugins} Assets/VLCUnity/Plugins/x86_64
        - rm -rf Assets/VLCUnity/Plugins/x86_64/lua/http
        - cp -r ./build/vlc-4.0.0-dev/sdk/ PluginSource/
        - ./build.sh
    after_script:
        - cp Assets/VLCUnity/Plugins/x86_64/VLCUnityPlugin.dll nightlies

libvlc-x86_64-debug:
    extends: .win-common
    image: 
        name: $VLC_WIN_LLVM_IMAGE
    variables:
        ARGS: -c -z -d -x -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64-debug.7z
        BUILD_FOLDER: win64
        
libvlc-x86_64:
    extends: .win-common
    image: 
        name: $VLC_WIN_LLVM_IMAGE
    variables:
        ARGS: -c -z -r -x -a x86_64 -i nope
        ARTIFACT: vlc-4.0.0-dev-win64.7z
        BUILD_FOLDER: win64

libvlc-uwp64-llvm:
    extends: .win-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        ARGS: -w -u -c -z -r -x -a x86_64 -i nope
        ARTIFACT: vlc-4.0.0-dev-win64.7z
        BUILD_FOLDER: win64-uwp

libvlc-uwp64-llvm-debug:
    extends: .win-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        ARGS: -w -u -c -z -d -x -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64-debug.7z
        BUILD_FOLDER: win64-uwp
            
libvlcsharp-unity:
    extends: .base-template
    script:
        - wget https://download.visualstudio.microsoft.com/download/pr/0c795076-b679-457e-8267-f9dd20a8ca28/02446ea777b6f5a5478cd3244d8ed65b/dotnet-sdk-3.1.300-linux-x64.tar.gz
        - mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.300-linux-x64.tar.gz -C $HOME/dotnet
        - export DOTNET_ROOT=$HOME/dotnet
        - export PATH=$PATH:$HOME/dotnet
        - dotnet --version
        - mkdir tmp && cd tmp && git clone https://code.videolan.org/videolan/LibVLCSharp lvs
        - cd lvs
        - git checkout -f master
        - git apply buildsystem/linux.patch
        - dotnet build src/LibVLCSharp/LibVLCSharp.csproj /p:UNITY=true -c Release
    after_script:
        - mkdir nightlies
        - cp tmp/lvs/src/LibVLCSharp/bin/Release/netstandard2.0/LibVLCSharp.dll nightlies

unity-plugin-windows:
    extends: .build-plugin-base

unity-plugin-windows-trial:
    extends: .build-plugin-base
    before_script:
        - wget -O trial.patch https://code.videolan.org/snippets/1250/raw
        - git apply trial.patch
